apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app_name: mylocalservice
  name: mylocalservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app_name: mylocalservice
  strategy: {}
  template:
    metadata:
      labels:
        app_name: mylocalservice
    spec:
      volumes:
      - name: mylocalservice-env
        configMap:
          name: mylocalservice-env
          defaultMode: 420
      containers:
        - image: mylocalservice.azurecr.io/main
          imagePullPolicy: Always
          name: mylocalservice
          ports:
            - containerPort: 4000
              name: port-4000
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 512Mi
            requests:
              cpu: 800m
              memory: 512Mi
          volumeMounts:
          - name: mylocalservice-env
            mountPath: /mylocal_service/.env
            subPath: .env
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
